### ISSUE TITLE
Working with v1.0.9

### ISSUE THREAD

**Issue by dankohn** [gkop/elastic-beanstalk-ruby#10]
To work with "64bit Amazon Linux 2014.09 v1.0.9 running Ruby 2.1 (Puma)" I found that only the following `.ebextensions/ruby.config` was necessary:

```yaml
option_settings:
  - option_name: RAILS_ENV
    value: "production"

packages:
  yum:
    git: []
    postgresql93-devel: []
```
